build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "breakpad/1.0.0"
    CONAN_USERNAME: "shinichy"
    CONAN_CHANNEL: "ci"
    CONAN_TOTAL_PAGES: 1

    matrix:
        - CONAN_CURRENT_PAGE: 1

install:
  - git clone https://chromium.googlesource.com/external/gyp
  - cd gyp
  - python setup.py install
  - cd ..
  - set PATH=%PATH%;%PYTHON%/Scripts/;%PYTHON%/lib/site-packages/
  - gyp -h
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
